spring.application.name=Blockchain Network Application
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/transaction_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Kumar@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML5
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# Server Configuration
server.port=8080
server.servlet.context-path=/blockchain_network

# Application Configuration
app.node.current=1
app.node.max=10
app.encryption.algorithms=AFFINE,CAESAR,BLOCK

# Logging Configuration
logging.level.com.blockchain=DEBUG
logging.level.org.springframework.web=DEBUG